import { motion } from "framer-motion";
import {
  FileCheck,
  Scale,
  CreditCard,
  Truck,
  ShieldCheck,
  Building2,
  AlertCircle,
  Clock,
  CheckCircle2
} from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function TermsConditions() {
  const lastUpdated = "August 2026";

  return (
    <div className="min-h-screen bg-brand-slateDark text-white flex flex-col selection:bg-brand-amber selection:text-brand-slateDark">
      <Navbar />

      <main className="flex-1 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header Badge & Title */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center space-y-4 mb-12"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-brand-amber/10 border border-brand-amber/30 text-brand-amber text-xs font-bold uppercase tracking-widest">
            <Scale className="w-4 h-4" />
            Commercial B2B Terms of Supply
          </div>
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-serif font-bold text-white tracking-tight">
            Terms & Conditions
          </h1>
          <p className="text-slate-400 text-sm sm:text-base max-w-2xl mx-auto leading-relaxed">
            Governing dealership authorization, quotation inquiries, Proforma Invoices, commercial Purchase Orders, payment schedules, and machinery dispatch.
          </p>
          <div className="text-xs text-slate-500 font-semibold tracking-wider uppercase">
            Effective Date: {lastUpdated} | Manufacturer: Durga Manufactures (Brand: Millzon)
          </div>
        </motion.div>

        {/* Content Sections */}
        <div className="space-y-8 text-sm sm:text-base leading-relaxed text-slate-300">
          {/* Section 1 */}
          <motion.section
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-slate-900/60 border border-slate-800 rounded-xl p-6 sm:p-8 space-y-4 shadow-xl"
          >
            <div className="flex items-center gap-3 text-brand-amber font-bold text-lg">
              <Building2 className="w-5 h-5 text-brand-amber" />
              <h2>1. Authorized Dealership & Account Approval</h2>
            </div>
            <p>
              Access to wholesale factory pricing, bulk quotation requests, and commercial equipment orders is reserved exclusively for verified B2B machinery dealers, distributors, and industrial clients approved by <strong>Durga Manufactures</strong>.
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-300 text-xs sm:text-sm pl-2">
              <li>Dealers must supply a valid GSTIN, business address, and authorized contact information upon registration.</li>
              <li>Admin retains the right to approve, reject, or suspend dealer accounts and assign specific discount slabs based on regional performance and trading terms.</li>
            </ul>
          </motion.section>

          {/* Section 2 */}
          <motion.section
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-slate-900/60 border border-slate-800 rounded-xl p-6 sm:p-8 space-y-4 shadow-xl"
          >
            <div className="flex items-center gap-3 text-brand-amber font-bold text-lg">
              <FileCheck className="w-5 h-5 text-brand-amber" />
              <h2>2. Quotations, Inquiries & Supplier-Specific Pricing</h2>
            </div>
            <p>
              Prices displayed on the digital catalogue serve as indicative baseline rates. Because machine specifications, electrical motor configurations, and supplier costs differ:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-300 text-xs sm:text-sm pl-2">
              <li><strong>Inquiry Submission:</strong> Inquiries submitted through the dealer portal do not constitute a binding contract until confirmed via an official Proforma Invoice (PI) generated by the Factory Admin.</li>
              <li><strong>Custom Supplier Pricing:</strong> Different rates may be applied for different authorized dealers, raw material suppliers, or specialized machine customizations.</li>
              <li><strong>Validity Period:</strong> Proforma Invoices remain valid for <strong>15 days</strong> from the date of issuance unless extended in writing.</li>
            </ul>
          </motion.section>

          {/* Section 3 */}
          <motion.section
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-slate-900/60 border border-slate-800 rounded-xl p-6 sm:p-8 space-y-4 shadow-xl"
          >
            <div className="flex items-center gap-3 text-brand-amber font-bold text-lg">
              <CreditCard className="w-5 h-5 text-brand-amber" />
              <h2>3. Commercial Payment Terms & Taxation</h2>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-1">
              <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 space-y-2">
                <span className="text-brand-amber font-bold text-sm block uppercase tracking-wider">Standard Payment Schedule</span>
                <p className="text-xs text-slate-300 leading-relaxed">
                  <strong>50% Advance</strong> upon confirmation of Proforma Invoice / issuance of Purchase Order, and <strong>50% Balance Payment</strong> prior to factory dispatch from Rajkot.
                </p>
              </div>
              <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 space-y-2">
                <span className="text-emerald-400 font-bold text-sm block uppercase tracking-wider">Statutory GST & Banking</span>
                <p className="text-xs text-slate-300 leading-relaxed">
                  All commercial billing includes applicable 18% GST (CGST + SGST for Gujarat, IGST for Interstate). Payments must be remitted strictly to Durga Manufactures&apos; designated Bank of Baroda account.
                </p>
              </div>
            </div>
          </motion.section>

          {/* Section 4 */}
          <motion.section
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-slate-900/60 border border-slate-800 rounded-xl p-6 sm:p-8 space-y-4 shadow-xl"
          >
            <div className="flex items-center gap-3 text-brand-amber font-bold text-lg">
              <Truck className="w-5 h-5 text-brand-amber" />
              <h2>4. Delivery, Freight & Factory Dispatch</h2>
            </div>
            <ul className="list-disc list-inside space-y-2 text-slate-300 text-xs sm:text-sm pl-2">
              <li><strong>Ex-Factory Terms:</strong> All machinery is supplied <strong>Ex-Factory, Rajkot (Gujarat)</strong>. Transportation, transit insurance, and unloading charges are payable by the buyer/dealer.</li>
              <li><strong>Signed PO Requirement:</strong> Machine assembly and dispatch scheduling commence only after receipt of a legally signed and stamped Purchase Order (PO).</li>
              <li><strong>Lead Times:</strong> Standard machinery dispatches within 7–14 working days from commercial locking; customized heavy industrial plants require 20–30 working days.</li>
            </ul>
          </motion.section>

          {/* Section 5 */}
          <motion.section
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-slate-900/60 border border-slate-800 rounded-xl p-6 sm:p-8 space-y-4 shadow-xl"
          >
            <div className="flex items-center gap-3 text-brand-amber font-bold text-lg">
              <ShieldCheck className="w-5 h-5 text-brand-amber" />
              <h2>5. Warranty & Factory Technical Support</h2>
            </div>
            <p>
              All Durga Manufactures (Millzon) machinery includes <strong>6 Months Limited Motor Warranty Only</strong> covering electric motor manufacturing defects under standard prescribed operating parameters.
            </p>
            <div className="bg-amber-500/10 border border-amber-500/30 p-4 rounded-lg text-amber-200 text-xs sm:text-sm space-y-2">
              <p className="font-bold text-brand-amber">⚠️ Important Warranty Exclusions:</p>
              <ul className="list-disc list-inside space-y-1.5 text-slate-300">
                <li><strong>No Warranty on Wear & Tear Parts:</strong> Wear-and-tear and high-friction components such as <strong>Jali (screens / sieves)</strong>, <strong>Beaters / Bitters (hammers / cutters)</strong>, blades, and belts are strictly <strong>NOT</strong> covered under warranty.</li>
                <li><strong>No Warranty on Machine Breakage:</strong> If any part of the machine, casting, chamber, or frame is broken, cracked, or damaged due to stones, metal parts, foreign objects, overloading, or physical impact, it will <strong>NOT</strong> be included or covered under warranty.</li>
                <li><strong>Electrical & Operation Limits:</strong> Damage caused by phase reversals, low voltage, power surges, or running without authorized motor starters is strictly excluded.</li>
              </ul>
            </div>
          </motion.section>

          {/* Section 6 */}
          <motion.section
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-slate-900/60 border border-slate-800 rounded-xl p-6 sm:p-8 space-y-4 shadow-xl"
          >
            <div className="flex items-center gap-3 text-brand-amber font-bold text-lg">
              <Scale className="w-5 h-5 text-brand-amber" />
              <h2>6. Jurisdiction & Dispute Resolution</h2>
            </div>
            <p>
              All quotations, purchase orders, commercial agreements, and dealership transactions are governed by the laws of India. Any legal dispute or claim arising shall be subject to the <strong>exclusive jurisdiction of the courts in Rajkot, Gujarat (India)</strong>.
            </p>
          </motion.section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
